name = "BEAVARs"
uuid = "93a03eec-7b33-4fd3-aded-846a82f4850b"
authors = ["Boris Blagov <46528899+borisblagov@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DelimitedFiles = "1.9.1"
Distributions = "0.25.118"
Documenter = "1.9.0"
LinearAlgebra = "1.11.0"
SparseArrays = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
